export const projects = [
  {
    title: 'Adminsite PBL5',
    description: 'This project is a website for booking movie tickets online. My part is to create an admin website. It was developed with JavaScript, css, Html. The feature I have invested most in is a revenue chart that displays daily, weekly, monthly and yearly data. Here, the administrator can manage movie management, account management, cast management, transaction management, and more.',
    descriptionJP: "このプロジェクトはオンラインで映画のチケットを予約するウェブサイトです。 私の部分は管理者のウェブサイトを作ることです。これは「JavaScript,css,Html」で開発しました。 私が最も投資した機能は、日、週、月、年ごとのデータを表示する収益チャートです。 ここで、管理者は映画の管理、アカウント管理、キャスト管理、取引管理などについて管理することができます。",
    descriptionVN: 'Dự án này là một trang web đặt vé xem phim trực tuyến. Phần của tôi là tạo một trang web admin quản lý hệ thống. Được phát triển với ngôn ngữ JavaScript, Css, Html. Tính năng mà tôi đã đầu tư nhiều nhất là biểu đồ doanh thu hiển thị dữ liệu hàng ngày, hàng tuần, hàng tháng và hàng năm. Tại đây, quản trị viên có thể quản lý quản lý phim, quản lý tài khoản, quản lý dàn diễn viên, quản lý giao dịch, v.v.',
      image: 'https://firebasestorage.googleapis.com/v0/b/musicupload-7dde0.appspot.com/o/Persional%2F1.png?alt=media&token=6a7080ce-4b79-4dff-af77-1a305022cb42',
      tags: ['MySQL', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    visit: 'https://pbl5-adminsite.netlify.app/',
    id: 0,
  },
  {
    title: 'E-Commerce',
    description:"Build and deploy an eCommerce website based on ReactJS. In addition, using Commerce.js provides full functionality of a sales website including steps like product posting, category, checkout,...",
    descriptionJP: '「ReactJS」に基づいてeコマースウェッブサイトを構築および展開します。さらに、「Commerce.js」を使用すると、製品の投稿、カテゴリ、チェックアウトなどの手順を含む、販売ウェッブサイトの全機能が提供されます。',
    descriptionVN: 'Xây dựng và triển khai trang web Thương mại điện tử dựa trên ReactJS. Ngoài ra, sử dụng Commerce.js cung cấp đầy đủ chức năng của một website bán hàng bao gồm các bước như đăng sản phẩm, danh mục, thanh toán, ...',
    image: 'https://firebasestorage.googleapis.com/v0/b/musicupload-7dde0.appspot.com/o/Persional%2F2.png?alt=media&token=e79d11bb-524d-4e86-b12b-f40d2dbef329',
    tags: ['React', 'Commerce'],
    source: 'https://google.com',
    visit: 'https://e-commerce-demo-app.vercel.app/',
    id: 1,
  },
  {
    title: 'Travel Advisor',
    description: "This Travel Advisor application helps users to know the restaurants, hotels, attractions in the surrounding area. By integrating Maps using Geolocation, Google Maps API & Google Places API, fetching location-based API data, filtering data...",
    descriptionJP: 'このトリップアドバイザーアプリケーションは、ユーザーが周辺地域のレストラン、ホテル、アトラクションを知るのに役立ちます。 「Geolocation、Google Maps API、Google Places API」を使用してマップを統合し、位置ベースのAPIデータを取得し、データをフィルタリングします...',
    descriptionVN: 'Ứng dụng Cố vấn Du lịch này giúp người dùng biết được các nhà hàng, khách sạn,địa điểm thu hút ở xung quanh. Bằng cách tích hợp Bản đồ sử dụng Vị trí địa lý, API Google Maps & API Google Địa điểm, tìm nạp dữ liệu API dựa trên vị trí, lọc dữ liệu ...',  
    image: 'https://firebasestorage.googleapis.com/v0/b/musicupload-7dde0.appspot.com/o/Persional%2F3.png?alt=media&token=2bc0bb15-446b-47c3-af57-18036b317490',
      tags: ['React', 'RapidAPI', 'GgMaps API'],
    source: 'https://google.com',
    visit: 'https://travel-demo-app.vercel.app/',
    id: 2,
  },
  {
    title: 'JingMB3',
    description: "This is my group's Jing MB3 music player app project. This application aims to meet today's entertainment and music needs available online and offline. This application was developed in Java via Android Studio. My job is to design music online using Android Studio software using the data stored and uploaded in Firebase. Through an app I made with another friend. The hardest step is a team meeting to edit and integrate the application's interface. Users can create and manage used playlists, albums, artists, etc. offline.",
    descriptionJP: 'これは私のグループのJingMB3音楽プレーヤーアプリプロジェクトです。このアプリは、オンラインとオフラインで利用できる今日のエンターテインメントと音楽のニーズを満たすことを目的です。 このアプリは、「AndroidStudio」を介してジャヴァで開発しました。私の役目は、Firebaseに保存されアップロードされたデータを使用してAndroidスタジオソフトウェアを使用してオンラインで音楽をデザインすることです。別の友達と私が作ったアプリを通して。最も難しい段階は、アプリケーションのインターフェイスを編集および統合するためのチーム会議です。 ユーザーはオフラインで利用プレイリスト、アルバム、アーティストなどを作成および管理できます。',
    descriptionVN: 'Đây là dự án ứng dụng chơi nhạc Jing MB3 của nhóm mình. Ứng dụng này nhằm đáp ứng nhu cầu giải trí và nghe nhạc hiện nay trực tuyến và ngoại tuyến. Ứng dụng này được phát triển bằng Java thông qua Android Studio. Công việc của tôi là thiết kế nhạc trực tuyến bằng phần mềm Android Studio sử dụng dữ liệu được lưu trữ và tải lên trong Firebase. Thông qua một ứng dụng tôi đã thực hiện với một người bạn khác. Bước khó nhất là họp nhóm để chỉnh sửa và tích hợp giao diện của ứng dụng. Người dùng có thể tạo và quản lý danh sách phát, album, nghệ sĩ, v.v. đã sử dụng ngoại tuyến.',
    image: 'https://firebasestorage.googleapis.com/v0/b/musicupload-7dde0.appspot.com/o/Persional%2F4.png?alt=media&token=f0378471-eb18-4fdf-b385-264ce18ffe35',
    tags: ['Java', 'Firebase', 'Sqlite'],
    source: 'https://google.com',
    visit: 'https://github.com/HeyBabe-0312/JingMB3',
    id: 3,
  },
  {
    title: 'Cryptocurrency',
    description: "The Cryptocurrency App. I using advanced React best practices, State Management of Redux Toolkit, UI Creation of Ant Design, creating charts using Chart.js, and fetching data from multiple sources using RapidAPI.",
    descriptionJP: '暗号通貨アプリ。高度な「ReactJS」のベストプラクティス、「Redux Toolkit」の状態管理、「Ant Design」のUI作成、「Chart.js」を使用したグラフの作成、「RapidAPI」を使用した複数のソースからのデータの取得を使用しています。',
    descriptionVN: 'Ứng dụng tiền điện tử. Tôi sử dụng các phương pháp hay nhất về React nâng cao, Quản lý trạng thái của Bộ công cụ Redux, Tạo giao diện người dùng của Thiết kế Kiến, tạo biểu đồ bằng Chart.js và tìm nạp dữ liệu từ nhiều nguồn bằng RapidAPI.',
    image: 'https://firebasestorage.googleapis.com/v0/b/musicupload-7dde0.appspot.com/o/Persional%2F5.png?alt=media&token=290c2f60-99e7-413b-a835-d03d1e6a7485',
    tags: ['React', 'Ant', 'Chart', 'RapidAPI'],
    source: 'https://google.com',
    visit: 'https://cryptocurrency-demo-app.vercel.app/',
    id: 4,
  },
  {
    title: 'Real Estate',
    description: "The Real Estate Application use ReactJS and NextJS. With rental homes and for-sale properties, advanced property filtering, property details page with an image carousel,...",
    descriptionJP: '不動産アプリケーションは「ReactJS」と「NextJS」を使用します。賃貸住宅と売り物件、高度な物件フィルタリング、画像カルーセル付きの物件詳細ページ、...',
    descriptionVN: 'Ứng dụng Bất động sản sử dụng ReactJS và NextJS. Với nhà cho thuê và tài sản bán, tính năng lọc tài sản nâng cao, trang chi tiết tài sản với băng chuyền hình ảnh, ...',
    image: 'https://firebasestorage.googleapis.com/v0/b/musicupload-7dde0.appspot.com/o/Persional%2F6.png?alt=media&token=ce0da9c9-e052-4907-ac68-b61407336f78',
    tags: ['React', 'Next', 'RapidAPI'],
    source: 'https://google.com',
    visit: 'https://modern-real-estate-demo-app.vercel.app/',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Start studying at Da Nang University of Technology.', textJP: 'ダナン工科大学で勉強を始めます。', textVN: 'Bắt đầu học tại Đại học Bách khoa Đà Nẵng.' },
  { year: 2020, text: 'Research and develop IOT and Mobile App.', textJP: 'IOTとモバイルアプリの研究と開発。', textVN: 'Nghiên cứu và phát triển IOT và ứng dụng Mobile.' },
  { year: 2021, text: 'Start learning about web development.', textJP: 'Web開発について学び始めます。', textVN: 'Bắt đầu tìm hiểu về phát triển web.' },
  { year: 2022, text: 'Proficient in basic web development.', textJP: '基本的なWeb開発に習熟している。', textVN: 'Thành thạo phát triển web cơ bản.' },
  { year: 2023, text: 'Work as Fullstack web developer.', textJP: 'フルスタックウェブ開発者として働きます。', textVN: 'Làm việc với tư cách lập trình viên phát triển web Fullstack.' },
  { year: 2025, text: 'Become a BrSE or Project Manager.', textJP: '「BrSE」とかプロジェクトマネージャーになります。', textVN: 'Trở thành BrSE hoặc Quản lý dự án.' },
];