export const projects = [
  {
    title: 'Modern Blog',
    description: "The Modern Blog App is the best GraphQL Blog Application with featured and recent posts, categories. full markdown articles, author information, comments, and much more. And what's best of all is that you or your clients can manage the blog from a dedicated Content Management System. Built with the newest technologies such as React JS, NextJS, Tailwind CSS, GraphQL, and GraphCMS.",
    descriptionJP: "最新のブログアプリは、注目の投稿や最近の投稿、カテゴリを備えた最高の「GraphQL」ブログアプリケーションです。完全な値下げ記事、著者情報、コメント、その他多数。そして何よりも優れているのは、あなたやあなたのクライアントが専用のコンテンツ管理システムからブログを管理できることです。 「ReactJS、NextJS、Tailwind CSS、GraphQL、GraphCMS」などの最新テクノロジーで構築されています。",
    descriptionVN: 'Ứng dụng Blog Hiện đại là Ứng dụng Blog GraphQL tốt nhất với các bài đăng, danh mục nổi bật và gần đây. đầy đủ các bài báo đánh dấu, thông tin tác giả, bình luận, và nhiều hơn nữa. Và điều tốt nhất là bạn hoặc khách hàng của bạn có thể quản lý blog từ Hệ thống quản lý nội dung chuyên dụng. Được xây dựng với các công nghệ mới nhất như React JS, NextJS, Tailwind CSS, GraphQL và GraphCMS.',
      image: 'https://firebasestorage.googleapis.com/v0/b/musicupload-7dde0.appspot.com/o/Image%2FmainBlogApp.png?alt=media&token=fd88eaa2-e894-491f-8d12-1e3b51150a7d',
      tags: ['Next', 'React', 'GraphQL', 'Tailwind'],
    source: 'https://google.com',
    visit: 'https://modern-blog-demo-app.vercel.app/',
    id: 0,
  },
  {
    title: 'E-Commerce',
    description:"Build and deploy an eCommerce website based on ReactJS. In addition, using Commerce.js provides full functionality of a sales website including steps like product posting, category, checkout,...",
    descriptionJP: '「ReactJS」に基づいてeコマースウェッブサイトを構築および展開します。さらに、「Commerce.js」を使用すると、製品の投稿、カテゴリ、チェックアウトなどの手順を含む、販売ウェッブサイトの全機能が提供されます。',
    descriptionVN: 'Xây dựng và triển khai trang web Thương mại điện tử dựa trên ReactJS. Ngoài ra, sử dụng Commerce.js cung cấp đầy đủ chức năng của một website bán hàng bao gồm các bước như đăng sản phẩm, danh mục, thanh toán, ...',
    image: 'https://firebasestorage.googleapis.com/v0/b/musicupload-7dde0.appspot.com/o/Persional%2F2.png?alt=media&token=e79d11bb-524d-4e86-b12b-f40d2dbef329',
    tags: ['React', 'Commerce'],
    source: 'https://google.com',
    visit: 'https://e-commerce-demo-app.vercel.app/',
    id: 1,
  },
  {
    title: 'Travel Advisor',
    description: "This Travel Advisor application helps users to know the restaurants, hotels, attractions in the surrounding area. By integrating Maps using Geolocation, Google Maps API & Google Places API, fetching location-based API data, filtering data...",
    descriptionJP: 'このトリップアドバイザーアプリケーションは、ユーザーが周辺地域のレストラン、ホテル、アトラクションを知るのに役立ちます。 「Geolocation、Google Maps API、Google Places API」を使用してマップを統合し、位置ベースのAPIデータを取得し、データをフィルタリングします...',
    descriptionVN: 'Ứng dụng Cố vấn Du lịch này giúp người dùng biết được các nhà hàng, khách sạn,địa điểm thu hút ở xung quanh. Bằng cách tích hợp Bản đồ sử dụng Vị trí địa lý, API Google Maps & API Google Địa điểm, tìm nạp dữ liệu API dựa trên vị trí, lọc dữ liệu ...',  
    image: 'https://firebasestorage.googleapis.com/v0/b/musicupload-7dde0.appspot.com/o/Persional%2F3.png?alt=media&token=2bc0bb15-446b-47c3-af57-18036b317490',
      tags: ['React', 'RapidAPI', 'GgMaps API'],
    source: 'https://google.com',
    visit: 'https://travel-demo-app.vercel.app/',
    id: 2,
  },
  {
    title: 'Budget Tracker',
    description: "Complex Expense Budget Tracker. Build it on React & JavaScript. Some of them are State Management in React, Context API, Local Storage, Material UI, and create a scalable React folder structure. But most importantly, you can use voice capabilities using Speechly.",
    descriptionJP: '複雑な経費予算トラッカー。 「ReactJS＆JavaScript」でビルドします。それらのいくつかは、「React」の状態管理、コンテキストAPI、ローカルストレージ、マテリアルUIであり、スケーラブルな「React」フォルダー構造を作成します。しかし、最も重要なことは、「Speechly」を使用して音声機能を使用できることです。',
    descriptionVN: 'Trình quản lí chi phí Ngân sách tiêu dùng phức tạp. Được xây dựng dựa trên ReactJS & JavaScript. Một số trong số đó là quản lí trạng thái trong React, API ngữ cảnh, LocalStorage, giao diện người dùng vật liệu và tạo cấu trúc thư mục React có thể mở rộng. Nhưng quan trọng nhất, bạn có thể sử dụng khả năng thoại bằng Speechly.',
    image: 'https://firebasestorage.googleapis.com/v0/b/musicupload-7dde0.appspot.com/o/Image%2FmainSpeech.png?alt=media&token=d30c3907-cb7e-4381-b1cb-fbd3354e4374',
    tags: ['React', 'Speechly', 'Chart'],
    source: 'https://google.com',
    visit: 'https://budget-tracker-demo-app.vercel.app/',
    id: 3,
  },
  {
    title: 'Cryptocurrency',
    description: "The Cryptocurrency App. I using advanced React best practices, State Management of Redux Toolkit, UI Creation of Ant Design, creating charts using Chart.js, and fetching data from multiple sources using RapidAPI.",
    descriptionJP: '暗号通貨アプリ。高度な「ReactJS」のベストプラクティス、「Redux Toolkit」の状態管理、「Ant Design」のUI作成、「Chart.js」を使用したグラフの作成、「RapidAPI」を使用した複数のソースからのデータの取得を使用しています。',
    descriptionVN: 'Ứng dụng tiền điện tử. Tôi sử dụng các phương pháp hay nhất về React nâng cao, Quản lý trạng thái của Bộ công cụ Redux, Tạo giao diện người dùng của Thiết kế Kiến, tạo biểu đồ bằng Chart.js và tìm nạp dữ liệu từ nhiều nguồn bằng RapidAPI.',
    image: 'https://firebasestorage.googleapis.com/v0/b/musicupload-7dde0.appspot.com/o/Persional%2F5.png?alt=media&token=290c2f60-99e7-413b-a835-d03d1e6a7485',
    tags: ['React', 'Ant', 'Chart', 'RapidAPI'],
    source: 'https://google.com',
    visit: 'https://cryptocurrency-demo-app.vercel.app/',
    id: 4,
  },
  {
    title: 'Real Estate',
    description: "The Real Estate Application use ReactJS and NextJS. With rental homes and for-sale properties, advanced property filtering, property details page with an image carousel,...",
    descriptionJP: '不動産アプリケーションは「ReactJS」と「NextJS」を使用します。賃貸住宅と売り物件、高度な物件フィルタリング、画像カルーセル付きの物件詳細ページ、...',
    descriptionVN: 'Ứng dụng Bất động sản sử dụng ReactJS và NextJS. Với nhà cho thuê và tài sản bán, tính năng tìm kiếm nâng cao, trang chi tiết tài sản với băng chuyền hình ảnh, ...',
    image: 'https://firebasestorage.googleapis.com/v0/b/musicupload-7dde0.appspot.com/o/Persional%2F6.png?alt=media&token=ce0da9c9-e052-4907-ac68-b61407336f78',
    tags: ['React', 'Next', 'RapidAPI'],
    source: 'https://google.com',
    visit: 'https://modern-real-estate-demo-app.vercel.app/',
    id: 5,
  },
  {
    title: 'Adminsite PBL5',
    description: 'This project is a website for booking movie tickets online. My part is to create an admin website. It was developed with JavaScript, css, Html. The feature I have invested most in is a revenue chart that displays daily, weekly, monthly and yearly data. Here, the administrator can manage movie management, account management, cast management, transaction management, and more.',
    descriptionJP: "このプロジェクトはオンラインで映画のチケットを予約するウェブサイトです。 私の部分は管理者のウェブサイトを作ることです。これは「JavaScript,css,Html」で開発しました。 私が最も投資した機能は、日、週、月、年ごとのデータを表示する収益チャートです。 ここで、管理者は映画の管理、アカウント管理、キャスト管理、取引管理などについて管理することができます。",
    descriptionVN: 'Dự án này là một trang web đặt vé xem phim trực tuyến. Phần của tôi là tạo một trang web admin quản lý hệ thống. Được phát triển với ngôn ngữ JavaScript, Css, Html. Tính năng mà tôi đã đầu tư nhiều nhất là biểu đồ doanh thu hiển thị dữ liệu hàng ngày, hàng tuần, hàng tháng và hàng năm. Tại đây, quản trị viên có thể quản lý quản lý phim, quản lý tài khoản, quản lý dàn diễn viên, quản lý giao dịch, v.v.',
      image: 'https://firebasestorage.googleapis.com/v0/b/musicupload-7dde0.appspot.com/o/Persional%2F1.png?alt=media&token=6a7080ce-4b79-4dff-af77-1a305022cb42',
      tags: ['MySQL', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    visit: 'https://pbl5-adminsite.netlify.app/',
    id: 6,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Start studying at Da Nang University of Technology.', textJP: 'ダナン工科大学で勉強を始めます。', textVN: 'Bắt đầu học tại Đại học Bách khoa Đà Nẵng.' },
  { year: 2020, text: 'Research and develop IOT and Mobile App.', textJP: 'IOTとモバイルアプリの研究と開発。', textVN: 'Nghiên cứu và phát triển IOT và ứng dụng Mobile.' },
  { year: 2021, text: 'Start learning about web development.', textJP: 'Web開発について学び始めます。', textVN: 'Bắt đầu tìm hiểu về phát triển web.' },
  { year: 2022, text: 'Proficient in basic web development.', textJP: '基本的なWeb開発に習熟している。', textVN: 'Thành thạo phát triển web cơ bản.' },
  { year: 2023, text: 'Work as Fullstack web developer.', textJP: 'フルスタックウェブ開発者として働きます。', textVN: 'Làm việc với tư cách lập trình viên phát triển web Fullstack.' },
  { year: 2025, text: 'Become a BrSE or Project Manager.', textJP: '「BrSE」とかプロジェクトマネージャーになります。', textVN: 'Trở thành BrSE hoặc Quản lý dự án.' },
];